In [6]:
import pandas as pd

In [7]:
orders = pd.read_csv("olist_orders_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
order_reviews = pd.read_csv("olist_order_reviews_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")
customers = pd.read_csv("olist_customers_dataset.csv")
sellers = pd.read_csv("olist_sellers_dataset.csv")
geo = pd.read_csv("olist_geolocation_dataset.csv")
payments = pd.read_csv("olist_order_payments_dataset.csv")

In [8]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

## Nivel 1, la mayoria son groupby, no pivot_tables

In [9]:
df1 = order_items.merge(products, on="product_id", how="left")[["order_id","price","product_category_name"]]
df1

                                order_id   price   product_category_name
0       00010242fe8c5a6d1ba2dd792cb16214   58.90              cool_stuff
1       00018f77f2f0320c557190d7a144bdd3  239.90                pet_shop
2       000229ec398224ef6ca0657da4fc703e  199.00        moveis_decoracao
3       00024acbcdf0a6daa1e931b038114c75   12.99              perfumaria
4       00042b26cf59d7ce69dfabb4e55b4fd9  199.90      ferramentas_jardim
...                                  ...     ...                     ...
112645  fffc94f6ce00a00581880bf54a75a037  299.99   utilidades_domesticas
112646  fffcd46ef2263f404302a634eb57f7eb  350.00  informatica_acessorios
112647  fffce4705a9662cd70adb13d4a31832d   99.90           esporte_lazer
112648  fffe18544ffabc95dfada21779c9644f   55.99  informatica_acessorios
112649  fffe41c64501cc87c801fd61db3f6244   43.00         cama_mesa_banho

[112650 rows x 3 columns]

In [10]:
df1.pivot_table(
    values="price",
    index='order_id',
    columns='product_category_name',
    aggfunc='mean',
    )

product_category_name,agro_industria_e_comercio,alimentos,alimentos_bebidas,artes,artes_e_artesanato,artigos_de_festas,artigos_de_natal,audio,automotivo,bebes,...,pet_shop,portateis_casa_forno_e_cafe,portateis_cozinha_e_preparadores_de_alimentos,relogios_presentes,seguros_e_servicos,sinalizacao_e_seguranca,tablets_impressao_imagem,telefonia,telefonia_fixa,utilidades_domesticas
order_id,,,,,,,,,,,,,,,,,,,,,
00010242fe8c5a6d1ba2dd792cb16214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00018f77f2f0320c557190d7a144bdd3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,239.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
000229ec398224ef6ca0657da4fc703e,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00024acbcdf0a6daa1e931b038114c75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00042b26cf59d7ce69dfabb4e55b4fd9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fffc94f6ce00a00581880bf54a75a037,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,299.99
fffcd46ef2263f404302a634eb57f7eb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fffce4705a9662cd70adb13d4a31832d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fffe18544ffabc95dfada21779c9644f,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fffe41c64501cc87c801fd61db3f6244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Nivel 2

6.- Construye una pivot table donde las filas representen la categoría del producto y las columnas representen el estado del pedido. Muestra el precio total.

In [11]:
# primero hacemos un merge entre orders y products
df2 = orders.merge(order_items, on="order_id", how="left")
df_2 = df2.merge(products, on="product_id", how="left")
Precio_total = df_2.pivot_table(
    values="price",
    index= "product_category_name",
    columns="order_status",
    aggfunc= "sum"
)
Precio_total

order_status,approved,canceled,delivered,invoiced,processing,shipped,unavailable
product_category_name,,,,,,,
agro_industria_e_comercio,NaN,NaN,70566.10,19.50,NaN,1944.87,NaN
alimentos,NaN,149.90,28731.15,NaN,221.60,290.76,NaN
alimentos_bebidas,NaN,60.00,14942.88,62.80,8.00,105.80,NaN
artes,NaN,35.00,23657.30,NaN,224.90,285.44,NaN
artes_e_artesanato,NaN,NaN,1814.01,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
sinalizacao_e_seguranca,NaN,NaN,21315.05,NaN,139.90,54.28,NaN
tablets_impressao_imagem,NaN,NaN,7528.41,NaN,NaN,NaN,NaN
telefonia,NaN,1324.89,309860.23,4654.13,4475.14,3353.14,NaN
telefonia_fixa,NaN,1758.79,55315.21,NaN,2492.50,16.50,NaN
utilidades_domesticas,169.9,5422.86,615628.69,1005.68,1858.23,8163.30,NaN

7.- Repite el ejercicio anterior utilizando el promedio del precio.

In [12]:
Promedio_total_del_precio = df_2.pivot_table(
    values="price",
    index= "product_category_name",
    columns="order_status",
    aggfunc= "mean"
)
Promedio_total_del_precio

order_status,approved,canceled,delivered,invoiced,processing,shipped,unavailable
product_category_name,,,,,,,
agro_industria_e_comercio,NaN,NaN,342.553883,19.500000,NaN,388.974000,NaN
alimentos,NaN,149.900000,57.577455,NaN,44.320000,58.152000,NaN
alimentos_bebidas,NaN,30.000000,55.549740,15.700000,8.000000,52.900000,NaN
artes,NaN,35.000000,120.087817,NaN,32.128571,71.360000,NaN
artes_e_artesanato,NaN,NaN,75.583750,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
sinalizacao_e_seguranca,NaN,NaN,108.198223,NaN,139.900000,54.280000,NaN
tablets_impressao_imagem,NaN,NaN,90.703735,NaN,NaN,NaN,NaN
telefonia,NaN,73.605000,69.945876,221.625238,248.618889,57.812759,NaN
telefonia_fixa,NaN,586.263333,216.922392,NaN,498.500000,16.500000,NaN
utilidades_domesticas,169.9,110.670612,90.600249,71.834286,68.823333,104.657692,NaN

8.- Construye una tabla que permita comparar el freight_value promedio entre categorías y estados del pedido.

In [13]:
print(orders.columns)
print(order_items.columns)
print(order_reviews.columns)
print(products.columns)
print(customers.columns)
print(sellers.columns)
print(geo.columns)
print(payments.columns)

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')
Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='str')
Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='str')
Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')
Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')
Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='str')
Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='str')
Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='str')

In [14]:
Flete_Promedio = df_2.pivot_table(
    values="freight_value",
    index= "product_category_name",
    columns="order_status",
    aggfunc= "mean"
)
Flete_Promedio

order_status,approved,canceled,delivered,invoiced,processing,shipped,unavailable
product_category_name,,,,,,,
agro_industria_e_comercio,NaN,NaN,27.365049,8.720000,NaN,39.536000,NaN
alimentos,NaN,17.760000,14.155371,NaN,15.614000,22.334000,NaN
alimentos_bebidas,NaN,9.685000,16.337881,11.850000,14.520000,15.905000,NaN
artes,NaN,16.600000,19.432640,NaN,19.108571,16.645000,NaN
artes_e_artesanato,NaN,NaN,15.422083,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
sinalizacao_e_seguranca,NaN,NaN,32.880914,NaN,18.550000,11.730000,NaN
tablets_impressao_imagem,NaN,NaN,14.773494,NaN,NaN,NaN,NaN
telefonia,NaN,14.022778,15.652910,12.056190,21.676667,16.855690,NaN
telefonia_fixa,NaN,15.990000,17.652275,NaN,14.880000,14.110000,NaN
utilidades_domesticas,9.56,19.178980,21.010090,18.502857,13.631852,23.193846,NaN

9.- Utiliza fill_value=0 y compara el resultado con la tabla original. ¿Qué combinaciones no tenían observaciones?

In [15]:
Flete_Promedio_fill = df_2.pivot_table(
    values="freight_value",
    index= "product_category_name",
    columns="order_status",
    aggfunc= "mean",
    fill_value= 0
)
Flete_Promedio_fill

order_status,approved,canceled,delivered,invoiced,processing,shipped,unavailable
product_category_name,,,,,,,
agro_industria_e_comercio,0.00,0.000000,27.365049,8.720000,0.000000,39.536000,0.0
alimentos,0.00,17.760000,14.155371,0.000000,15.614000,22.334000,0.0
alimentos_bebidas,0.00,9.685000,16.337881,11.850000,14.520000,15.905000,0.0
artes,0.00,16.600000,19.432640,0.000000,19.108571,16.645000,0.0
artes_e_artesanato,0.00,0.000000,15.422083,0.000000,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...
sinalizacao_e_seguranca,0.00,0.000000,32.880914,0.000000,18.550000,11.730000,0.0
tablets_impressao_imagem,0.00,0.000000,14.773494,0.000000,0.000000,0.000000,0.0
telefonia,0.00,14.022778,15.652910,12.056190,21.676667,16.855690,0.0
telefonia_fixa,0.00,15.990000,17.652275,0.000000,14.880000,14.110000,0.0
utilidades_domesticas,9.56,19.178980,21.010090,18.502857,13.631852,23.193846,0.0

10. Construye una pivot table utilizando más de una variable en index. Interpreta qué representa cada nivel del índice.

In [16]:
df_10 = df_2.pivot_table(
    values=["freight_value","price"],
    index= "product_category_name",
    columns="order_status",
    aggfunc= "mean",
    fill_value= 0
)
df_10

                          freight_value                                   \
order_status                   approved   canceled  delivered   invoiced
product_category_name
agro_industria_e_comercio          0.00   0.000000  27.365049   8.720000
alimentos                          0.00  17.760000  14.155371   0.000000
alimentos_bebidas                  0.00   9.685000  16.337881  11.850000
artes                              0.00  16.600000  19.432640   0.000000
artes_e_artesanato                 0.00   0.000000  15.422083   0.000000
...                                 ...        ...        ...        ...
sinalizacao_e_seguranca            0.00   0.000000  32.880914   0.000000
tablets_impressao_imagem           0.00   0.000000  14.773494   0.000000
telefonia                          0.00  14.022778  15.652910  12.056190
telefonia_fixa                     0.00  15.990000  17.652275   0.000000
utilidades_domesticas              9.56  19.178980  21.010090  18.502857

                                                               price  \
order_status              processing    shipped unavailable approved
product_category_name
agro_industria_e_comercio   0.000000  39.536000         0.0      0.0
alimentos                  15.614000  22.334000         0.0      0.0
alimentos_bebidas          14.520000  15.905000         0.0      0.0
artes                      19.108571  16.645000         0.0      0.0
artes_e_artesanato          0.000000   0.000000         0.0      0.0
...                              ...        ...         ...      ...
sinalizacao_e_seguranca    18.550000  11.730000         0.0      0.0
tablets_impressao_imagem    0.000000   0.000000         0.0      0.0
telefonia                  21.676667  16.855690         0.0      0.0
telefonia_fixa             14.880000  14.110000         0.0      0.0
utilidades_domesticas      13.631852  23.193846         0.0    169.9

                                                                           \
order_status                 canceled   delivered    invoiced  processing
product_category_name
agro_industria_e_comercio    0.000000  342.553883   19.500000    0.000000
alimentos                  149.900000   57.577455    0.000000   44.320000
alimentos_bebidas           30.000000   55.549740   15.700000    8.000000
artes                       35.000000  120.087817    0.000000   32.128571
artes_e_artesanato           0.000000   75.583750    0.000000    0.000000
...                               ...         ...         ...         ...
sinalizacao_e_seguranca      0.000000  108.198223    0.000000  139.900000
tablets_impressao_imagem     0.000000   90.703735    0.000000    0.000000
telefonia                   73.605000   69.945876  221.625238  248.618889
telefonia_fixa             586.263333  216.922392    0.000000  498.500000
utilidades_domesticas      110.670612   90.600249   71.834286   68.823333


order_status                  shipped unavailable
product_category_name
agro_industria_e_comercio  388.974000         0.0
alimentos                   58.152000         0.0
alimentos_bebidas           52.900000         0.0
artes                       71.360000         0.0
artes_e_artesanato           0.000000         0.0
...                               ...         ...
sinalizacao_e_seguranca     54.280000         0.0
tablets_impressao_imagem     0.000000         0.0
telefonia                   57.812759         0.0
telefonia_fixa              16.500000         0.0
utilidades_domesticas      104.657692         0.0

[73 rows x 14 columns]

11. Crea una columna llamada total que sea la suma de price y freight_value.

In [17]:
total= df_2.pivot_table(
    values=["freight_value","price"],
    index= "product_category_name",
    columns="order_status",
    aggfunc= "sum",
    fill_value= 0
)
total

                          freight_value                               \
order_status                   approved canceled  delivered invoiced
product_category_name
agro_industria_e_comercio          0.00     0.00    5637.20     8.72
alimentos                          0.00    17.76    7063.53     0.00
alimentos_bebidas                  0.00    19.37    4394.89    47.40
artes                              0.00    16.60    3828.23     0.00
artes_e_artesanato                 0.00     0.00     370.13     0.00
...                                 ...      ...        ...      ...
sinalizacao_e_seguranca            0.00     0.00    6477.54     0.00
tablets_impressao_imagem           0.00     0.00    1226.20     0.00
telefonia                          0.00   252.41   69342.39   253.18
telefonia_fixa                     0.00    47.97    4501.33     0.00
utilidades_domesticas              9.56   939.77  142763.56   259.04

                                                             price           \
order_status              processing  shipped unavailable approved canceled
product_category_name
agro_industria_e_comercio       0.00   197.68         0.0      0.0     0.00
alimentos                      78.07   111.67         0.0      0.0   149.90
alimentos_bebidas              14.52    31.81         0.0      0.0    60.00
artes                         133.76    66.58         0.0      0.0    35.00
artes_e_artesanato              0.00     0.00         0.0      0.0     0.00
...                              ...      ...         ...      ...      ...
sinalizacao_e_seguranca        18.55    11.73         0.0      0.0     0.00
tablets_impressao_imagem        0.00     0.00         0.0      0.0     0.00
telefonia                     390.18   977.63         0.0      0.0  1324.89
telefonia_fixa                 74.40    14.11         0.0      0.0  1758.79
utilidades_domesticas         368.06  1809.12         0.0    169.9  5422.86


order_status               delivered invoiced processing  shipped unavailable
product_category_name
agro_industria_e_comercio   70566.10    19.50       0.00  1944.87         0.0
alimentos                   28731.15     0.00     221.60   290.76         0.0
alimentos_bebidas           14942.88    62.80       8.00   105.80         0.0
artes                       23657.30     0.00     224.90   285.44         0.0
artes_e_artesanato           1814.01     0.00       0.00     0.00         0.0
...                              ...      ...        ...      ...         ...
sinalizacao_e_seguranca     21315.05     0.00     139.90    54.28         0.0
tablets_impressao_imagem     7528.41     0.00       0.00     0.00         0.0
telefonia                  309860.23  4654.13    4475.14  3353.14         0.0
telefonia_fixa              55315.21     0.00    2492.50    16.50         0.0
utilidades_domesticas      615628.69  1005.68    1858.23  8163.30         0.0

[73 rows x 14 columns]

12. Crea una columna que clasifique los productos como "barato" o "caro" según un umbral que tú determines. Justifica el umbral.

In [18]:
df12 = order_items
df12["flete_codo"] = df12.apply(
    lambda fila:'caro' if fila['freight_value'] > 100
    else 'barato',
    axis=1
)
df12

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,flete_codo
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,barato
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,barato
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,barato
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,barato
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,barato
...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,barato
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,barato
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,barato
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,barato
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,barato

13.Crea una columna que indique si el costo de envío representa más del 20% del precio del producto.

In [19]:
df13 = df12
df13["flete_20%"]=df13.apply(
    lambda fila:"Si" if fila ["freight_value"] >= fila["price"]*0.20
    else "No",
    axis= 1
)
df13

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,flete_codo,flete_20%
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,barato,Si
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,barato,No
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,barato,No
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,barato,Si
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,barato,No
...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,barato,No
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,barato,No
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,barato,No
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,barato,No
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,barato,Si

14.Crea una nueva columna que convierta el nombre de la categoría a mayúsculas.

In [46]:
df14 = products
df14 = df14.dropna(subset = "product_category_name").copy()
df14["Nombre_Cat_Mayusc"] = df14["product_category_name"].apply(
    lambda x : x.upper()
)
df14
# no estoy seguro como se hace usando lambda

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,Nombre_Mayusc,contiene_palabra,Nombre_Cat_Mayusc
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,PERFUMARIA,False,PERFUMARIA
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,ARTES,True,ARTES
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,ESPORTE_LAZER,False,ESPORTE_LAZER
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,BEBES,False,BEBES
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,UTILIDADES_DOMESTICAS,False,UTILIDADES_DOMESTICAS
...,...,...,...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0,MOVEIS_DECORACAO,False,MOVEIS_DECORACAO
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0,CONSTRUCAO_FERRAMENTAS_ILUMINACAO,False,CONSTRUCAO_FERRAMENTAS_ILUMINACAO
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0,CAMA_MESA_BANHO,False,CAMA_MESA_BANHO
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0,INFORMATICA_ACESSORIOS,False,INFORMATICA_ACESSORIOS
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0,CAMA_MESA_BANHO,False,CAMA_MESA_BANHO

In [ ]:
df14_2 = products
df14_2["Nombre_Mayusc"] = df14_2["product_category_name"].str.upper()
df14_2

15.Crea una columna que indique si el nombre de la categoría contiene una palabra determinada.

In [53]:
df15 = products
df15 = df15.dropna(subset = "product_category_name").copy()
df15["contiene_palabra"] = df15["product_category_name"].apply(
    lambda x:"artes" in x.lower()
)
df15

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,Nombre_Mayusc,contiene_palabra
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,PERFUMARIA,False
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,ARTES,True
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,ESPORTE_LAZER,False
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,BEBES,False
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,UTILIDADES_DOMESTICAS,False
...,...,...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0,MOVEIS_DECORACAO,False
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0,CONSTRUCAO_FERRAMENTAS_ILUMINACAO,False
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0,CAMA_MESA_BANHO,False
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0,INFORMATICA_ACESSORIOS,False
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0,CAMA_MESA_BANHO,False

## Nivel 4 — Lambda + pivot table

16. Crea una variable que clasifique los pedidos según el costo total y después construye una pivot table con el costo total promedio por categoría y segmento.

In [58]:
df16 = order_items.merge(products, on = "product_id", how= "left")
df16["costo_total"] = df16.apply(lambda fila: (fila["price"]+ fila["freight_value"]) , axis = 1)
df16["caro_o_barato"] = df16["costo_total"].apply(lambda x: "Caro" if x > 150 else "Barato")
df16.pivot_table(values="costo_total", index="product_category_name",columns="caro_o_barato", aggfunc="mean")

caro_o_barato                 Barato        Caro
product_category_name
agro_industria_e_comercio  58.557079  594.816992
alimentos                  61.773134  187.630244
alimentos_bebidas          54.104055  247.710000
artes                      92.680608  409.736429
artes_e_artesanato         67.209524  257.580000
...                              ...         ...
sinalizacao_e_seguranca    68.469007  316.602069
tablets_impressao_imagem   93.565125  423.133333
telefonia                  47.613979  334.555756
telefonia_fixa             63.473388  649.446667
utilidades_domesticas      67.945602  268.619237

[73 rows x 2 columns]

17. Calcula el porcentaje que representa el envío respecto al precio y crea una clasificación: "envío bajo" y "envío alto". Después compara ambas categorías mediante una pivot table.

In [62]:
df17 = df16
df17["porcentaje_envio"] = df17.apply(lambda fila: (fila["freight_value"]/fila["price"]), axis = 1)
df17["clasif"] = df17["porcentaje_envio"].apply(lambda x: "envio_alto" if x> 0.3 else "envio_bajo")
df17.pivot_table(values="freight_value", index ="product_category_name", columns="clasif", aggfunc="mean")

clasif                     envio_alto  envio_bajo
product_category_name
agro_industria_e_comercio   20.326269   30.908552
alimentos                   16.417128   12.919651
alimentos_bebidas           16.568366   15.278684
artes                       22.931268   17.514855
artes_e_artesanato          11.650000   19.194167
...                               ...         ...
sinalizacao_e_seguranca     43.657308   20.710105
tablets_impressao_imagem    19.856364   13.996944
telefonia                   16.104032   14.859830
telefonia_fixa              16.662281   18.255400
utilidades_domesticas       22.073819   20.000170

[73 rows x 2 columns]

18. Crea una variable que indique si el pedido tiene un precio superior al precio promedio de todos los productos. Después analiza esa variable mediante una pivot table.

In [83]:
df18 = df16
promedio = df18["price"].mean()
df18["variable_promedio"] = df18["price"].apply(lambda x:"superior al promedio" if x>promedio else "inferior al promedio")
df18.pivot_table(values= "price", index="product_category_name", columns="variable_promedio", aggfunc="count")

variable_promedio          inferior al promedio  superior al promedio
product_category_name
agro_industria_e_comercio                  88.0                 124.0
alimentos                                 466.0                  44.0
alimentos_bebidas                         255.0                  23.0
artes                                     185.0                  24.0
artes_e_artesanato                         16.0                   8.0
...                                         ...                   ...
sinalizacao_e_seguranca                   145.0                  54.0
tablets_impressao_imagem                   79.0                   4.0
telefonia                                3895.0                 650.0
telefonia_fixa                            165.0                  99.0
utilidades_domesticas                    5417.0                1547.0

[73 rows x 2 columns]

19. Crea una pivot table que muestre, para cada categoría, el total y el promedio de una variable numérica que consideres relevante.

In [ ]:
df19 = df16
df19.pivot_table(values="freight_value",index="product_category_name", aggfunc=["sum", "mean"])
#suma y promedio de los fletes por categoria

                                    sum          mean
                          freight_value freight_value
product_category_name
agro_industria_e_comercio       5843.60     27.564151
alimentos                       7271.03     14.256922
alimentos_bebidas               4507.99     16.215791
artes                           4045.17     19.354880
artes_e_artesanato               370.13     15.422083
...                                 ...           ...
sinalizacao_e_seguranca         6507.82     32.702613
tablets_impressao_imagem        1226.20     14.773494
telefonia                      71215.79     15.669041
telefonia_fixa                  4637.81     17.567462
utilidades_domesticas         146149.11     20.986374

[73 rows x 2 columns]

## Nivel 5 — Análisis libre

20. Formula una pregunta de negocio utilizando Olist que pueda responderse mediante una combinación de lambda, apply() y pivot_table().

Debes entregar:
La pregunta.
Las transformaciones realizadas.
La pivot table utilizada.
Una interpretación de los resultados.

In [102]:
# ¿Que categorias tiene la mayor cantidad de productos con el promedio de precios más alto?
df20 = df16
tabla = df20.pivot_table(values="price", index="product_category_name", aggfunc=["mean", "count"])
tabla.columns = ["precio_promedio", "cantidad_productos"]
tabla_ordenada = tabla.sort_values(by ="precio_promedio", ascending=False)
tabla_ordenada

                             precio_promedio  cantidad_productos
product_category_name
pcs                              1098.340542                 203
portateis_casa_forno_e_cafe       624.285658                  76
eletrodomesticos_2                476.124958                 238
agro_industria_e_comercio         342.124858                 212
instrumentos_musicais             281.616000                 680
...                                      ...                 ...
alimentos_bebidas                  54.602446                 278
cds_dvds_musicais                  52.142857                  14
fraldas_higiene                    40.194615                  39
flores                             33.637576                  33
casa_conforto_2                    25.342333                  30

[73 rows x 2 columns]

21. Investiga una posible relación entre precio, costo de envío y categoría de producto. Crea al menos una variable derivada con lambda y utiliza una pivot table para presentar tus resultados.

In [103]:
df21 = df16
df21["porcentaje_envio"] = df21.apply(lambda fila: (fila["freight_value"]/fila["price"]), axis = 1)
df21["clasif"] = df21["porcentaje_envio"].apply(lambda x: "envio_alto" if x> 0.3 else "envio_bajo")
df21.pivot_table(values="freight_value", index ="product_category_name", columns="clasif", aggfunc="mean")

clasif                     envio_alto  envio_bajo
product_category_name
agro_industria_e_comercio   20.326269   30.908552
alimentos                   16.417128   12.919651
alimentos_bebidas           16.568366   15.278684
artes                       22.931268   17.514855
artes_e_artesanato          11.650000   19.194167
...                               ...         ...
sinalizacao_e_seguranca     43.657308   20.710105
tablets_impressao_imagem    19.856364   13.996944
telefonia                   16.104032   14.859830
telefonia_fixa              16.662281   18.255400
utilidades_domesticas       22.073819   20.000170

[73 rows x 2 columns]

22. Construye un pequeño reporte que responda: ¿qué categorías presentan comportamientos diferentes dependiendo del estado del pedido? Utiliza al menos dos pivot tables y una transformación realizada con lambda.

In [121]:
df22 = df16.merge(orders, on="order_id", how="left")
df22 = df22[df22["order_status"].isin(["delivered", "canceled"])] #Aquí solo me quedo con los estatus entregado y cancelado
flete_prom = df22.pivot_table(values="freight_value", index="product_category_name", columns="order_status", aggfunc= lambda x: x.max()-x.min())
cancelaciones = df22.pivot_table(values="price", index="product_category_name", columns="order_status", aggfunc=lambda x: x.mean(), fill_value=0)

display(flete_prom, cancelaciones)

order_status               canceled  delivered
product_category_name
agro_industria_e_comercio       NaN     187.16
alimentos                      0.00      55.87
alimentos_bebidas              2.55      58.02
artes                          0.00     220.27
artes_e_artesanato              NaN      61.33
...                             ...        ...
sinalizacao_e_seguranca         NaN     293.41
tablets_impressao_imagem        NaN      32.78
telefonia                     16.57     121.21
telefonia_fixa                15.07      69.83
utilidades_domesticas         98.68     375.26

[73 rows x 2 columns]

order_status                 canceled   delivered
product_category_name
agro_industria_e_comercio    0.000000  342.553883
alimentos                  149.900000   57.577455
alimentos_bebidas           30.000000   55.549740
artes                       35.000000  120.087817
artes_e_artesanato           0.000000   75.583750
...                               ...         ...
sinalizacao_e_seguranca      0.000000  108.198223
tablets_impressao_imagem     0.000000   90.703735
telefonia                   73.605000   69.945876
telefonia_fixa             586.263333  216.922392
utilidades_domesticas      110.670612   90.600249

[73 rows x 2 columns]

Gracias a las siguientes tablas podemos ver que para cada función hay una variacion dependiendo al estatus de la orden. En la primera tabla podemos apreciar el flete proemdio de cada categoria por estado, el cual nos sirve para ubicar fletes muy altos, si alguna categoria tuviese un costo de flete mas elevado en cancelado que entregado, nos indicaría que el cliente decide no comprar cuando ve el costo del envio xd.
Mientras tanto, en la segunda tabla podemos apreciar cuales son las categorias las cuales concentran mayor numero de cancelaciones o entregas efectivas, donde podemos ver que entre resultados distan bastante, con categorias donde no se ha cancelado ninguna orden.