# CheatSheet  Tarea 2

1.- Importar Pandas

In [2]:
import pandas as pd

2.- Cargarémos nuestra Base de datos

In [3]:
df = pd.read_csv("base_generica_pandas.csv")

## Ahora conocerémos nuestro DataFrame
para ello explorarémos la estructura de los datos usando los siguientes comandos:

#### Ambos, head() y tail(), son acciones que nos muestran las primeras y las ultimas 5 columnas respectivamente, a no ser que coloquemos algún numero determinado en los paréntesis.

In [4]:
df.head()

     col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
0  380.79    49  56.4     1    B    Sur  0.294     5   No   Alto
1  951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
2  734.67    49  57.2     2    C  Norte  0.697     5   Sí   Alto
3  602.67    21  63.9     0    A  Norte  0.384     3   Sí   Alto
4  164.46    47  37.4     7    D    Sur  0.737     3   Sí  Medio

In [5]:
df.tail()

      col1  col2  col3  col4 col5   col6   col7  col8 col9 col10
95  498.86    43  47.7     8    B    Sur  0.459     2   Sí  Bajo
96  527.51    20  44.4     6    C   Este  0.842     2   Sí  Alto
97  433.27    36  30.6     3    D  Norte  0.769     3   Sí  Bajo
98   35.16    37  38.5     9    A  Norte  0.066     3   Sí  Bajo
99  116.81    49  56.3     4    B    Sur  0.046     5   Sí  Bajo

#### Como .shape y .columns no son acciones, no debemos poner los préntesis. Para el caso de ".shape", nos permite ver las filas (primer número) y las columnas (segundo número). 
#### El .columns nos permite ver la información de las columnas

In [6]:
df.shape

(100, 10)

In [7]:
df.columns

Index(['col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8', 'col9',
       'col10'],
      dtype='str')

# Ahora seleccionaremos columnas de nuestro DF.
 para ello usaremos ["NOMBRE DE LA COLUMNA"]

In [8]:
df["col1"]

0     380.79
1     951.21
2     734.67
3     602.67
4     164.46
       ...
95    498.86
96    527.51
97    433.27
98     35.16
99    116.81
Name: col1, Length: 100, dtype: float64

Usarémos doble corchete para que se vea mas bonito, podemos agregar más columnas

In [9]:
df[["col1","col10"]]

      col1  col10
0   380.79   Alto
1   951.21  Medio
2   734.67   Alto
3   602.67   Alto
4   164.46  Medio
..     ...    ...
95  498.86   Bajo
96  527.51   Alto
97  433.27   Bajo
98   35.16   Bajo
99  116.81   Bajo

[100 rows x 2 columns]


## Filtrar Datos
Nos quedarémos con los registros que cumplan una condición.

In [10]:
df[df["col1"]>500]

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
2   734.67    49  57.2     2    C  Norte  0.697     5   Sí   Alto
3   602.67    21  63.9     0    A  Norte  0.384     3   Sí   Alto
7   867.51    56  55.9     6    A  Norte  0.058     1   No   Bajo
8   605.10    62  40.6     9    A  Oeste  0.395     3   No  Medio
9   710.99    32  42.2     4    A    Sur  0.107     4   Sí  Medio
11  970.21    46  55.7     4    B    Sur  0.170     1   No   Bajo
12  834.12    53  50.9     6    A   Este  0.647     3   No   Alto
17  529.51    45  34.0     9    A  Norte  0.260     5   Sí   Bajo
20  615.73    62  63.8     5    D  Oeste  0.280     3   Sí   Alto
25  787.32    61  67.5     6    D  Oeste  0.076     2   No   Alto
27  519.09    47  33.6     5    B   Este  0.417     5   No   Bajo
28  596.49    28   6.8     6    D   Este  0.581     1   No   Bajo
30  611.47    42  49.9     9    D  Norte  0.083     1   No   Alto
33  949.40    18  33.3     5    A    Sur  0.165     2   No  Medio
34  965.98    44  63.0     8    C  Oeste  0.411     1   Sí   Bajo
35  810.31    30  64.4     4    A   Este  0.778     2   No   Bajo
38  687.39    56  84.1     4    B  Oeste  0.377     1   No  Medio
41  500.23    44  27.5     4    B   Este  0.829     1   No   Alto
43  910.23    54  56.2     3    D    Sur  0.064     5   Sí  Medio
45  665.90    59  63.1     4    B   Este  0.134     2   Sí   Alto
47  524.87    41  29.8     9    C   Este  0.075     1   Sí   Alto
48  551.24    32  62.8     9    C  Norte  0.692     1   Sí   Bajo
50  969.89    49  49.9     4    D    Sur  0.750     5   No   Bajo
51  777.38    41  26.4     3    D  Oeste  0.913     4   Sí   Bajo
52  940.10    58  72.2     1    A    Sur  0.585     2   Sí   Alto
53  895.88    29  56.0     3    A    Sur  0.726     4   No   Alto
54  601.92    56  23.3     9    C  Oeste  0.757     2   Sí  Medio
55  922.66    19  46.4     9    D  Oeste  0.378     5   No  Medio
62  830.45    40  35.8     7    D   Este  0.757     5   No   Alto
65  547.27    50  23.8     0    C    Sur  0.022     3   Sí  Medio
67  804.18    36  25.7     3    A   Este  0.476     1   No   Alto
69  987.02    61  70.8     1    C  Norte  0.308     4   No   Bajo
70  774.52    43  37.2     2    D  Norte  0.816     2   No  Medio
73  817.31    49  43.3     2    C    Sur  0.792     2   Sí   Bajo
74  709.79    21  56.3    10    A  Norte  0.590     4   Sí  Medio
75  731.72    28  39.1     4    D    Sur  0.480     1   No   Bajo
76  773.56    34  23.0     2    A    Sur  0.421     1   Sí   Bajo
80  864.47    51  39.0     9    C  Norte  0.903     4   No   Alto
81  627.07    23  52.9    10    A  Norte  0.617     2   No   Bajo
86  732.31    50  32.0     6    B  Norte  0.091     4   No   Bajo
87  641.18    26  68.0     0    C   Este  0.726     2   No   Alto
88  888.34    23  52.2     9    B  Oeste  0.547     1   No  Medio
91  716.11    20  21.8     9    C   Este  0.298     2   No  Medio
92  763.18    37  64.5     9    A   Este  0.524     1   No   Bajo
93  565.66    53  42.3     1    C  Oeste  0.698     5   Sí   Alto
94  773.26    36  68.2     2    C  Norte  0.796     4   Sí   Alto
96  527.51    20  44.4     6    C   Este  0.842     2   Sí   Alto

## Ordenar datos 
Se ordena el DF usando una o varias columnas

In [11]:
df.sort_values("col1")

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
72   15.47    23  63.2     0    D  Norte  0.088     1   No   Alto
10   30.38    60  50.2     9    D  Norte  0.336     4   No  Medio
98   35.16    37  38.5     9    A  Norte  0.066     3   Sí   Bajo
42   44.04    26  49.8     6    D    Sur  0.569     3   No   Bajo
58   54.78    34  48.1     0    D   Este  0.251     3   No   Alto
..     ...   ...   ...   ...  ...    ...    ...   ...  ...    ...
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
34  965.98    44  63.0     8    C  Oeste  0.411     1   Sí   Bajo
50  969.89    49  49.9     4    D    Sur  0.750     5   No   Bajo
11  970.21    46  55.7     4    B    Sur  0.170     1   No   Bajo
69  987.02    61  70.8     1    C  Norte  0.308     4   No   Bajo

[100 rows x 10 columns]

In [12]:
df.sort_values(["col1", "col3"])

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
72   15.47    23  63.2     0    D  Norte  0.088     1   No   Alto
10   30.38    60  50.2     9    D  Norte  0.336     4   No  Medio
98   35.16    37  38.5     9    A  Norte  0.066     3   Sí   Bajo
42   44.04    26  49.8     6    D    Sur  0.569     3   No   Bajo
58   54.78    34  48.1     0    D   Este  0.251     3   No   Alto
..     ...   ...   ...   ...  ...    ...    ...   ...  ...    ...
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
34  965.98    44  63.0     8    C  Oeste  0.411     1   Sí   Bajo
50  969.89    49  49.9     4    D    Sur  0.750     5   No   Bajo
11  970.21    46  55.7     4    B    Sur  0.170     1   No   Bajo
69  987.02    61  70.8     1    C  Norte  0.308     4   No   Bajo

[100 rows x 10 columns]

## Estadística descriptiva
Explorarémos las variables numéricas de nuestra base.
Como tds son acciones, ponemos ().

### Con la acción .describe() se nos abren un conjunto de cálculos  de todas las columnas con variables númericas. Entre ellas resaltan el contar los valores de cada columna, el promedio, desviación estándar, el mínimo , el máximo y los percentiles

In [13]:
df.describe()

             col1        col2        col3       col4        col7        col8
count  100.000000  100.000000  100.000000  100.00000  100.000000  100.000000
mean   475.479300   40.650000   48.323000    4.72000    0.493950    2.900000
std    294.514525   13.699056   15.726294    3.26314    0.291855    1.396243
min     15.470000   18.000000    6.800000    0.00000    0.014000    1.000000
25%    201.267500   28.000000   37.350000    2.00000    0.264500    2.000000
50%    469.500000   43.000000   49.900000    4.00000    0.480000    3.000000
75%    732.900000   50.250000   57.525000    8.00000    0.751750    4.000000
max    987.020000   65.000000   84.100000   10.00000    0.996000    5.000000

## PARA LAS SIGUIENTES ACCIONES TENEMOS EL SIGUIENTE RESULTADO:
* #### .mean()    --------->    promedio
* #### .median()  --------->    mediana
* #### .min()     --------->    mínimo
* #### .max()     --------->    máximo
* #### .std()     --------->    desviación estándar

para ejecutar estos códigos realizarémos lo siguiente: df["LA COLUMNA QUE QUERÉMOS"]. acción()

In [14]:
promedio = df["col1"].mean()
print(promedio)

475.4793000000001

In [15]:
df["col1"].median()

np.float64(469.5)

## Trabajar con variables categóricas

* Value_counts() -----> Sirve para contar cuantas veces se repite algún elemento
* unique() --------> Para mostrar los que no se repiten
* nunique() --------> Cuenta cuantos valores unicos hay en una columna

In [16]:
df["col10"].value_counts()

col10
Bajo     36
Alto     34
Medio    30
Name: count, dtype: int64

In [23]:
df["col10"].unique()

<StringArray>
['Alto', 'Medio', 'Bajo']
Length: 3, dtype: str

In [24]:
df["col10"].nunique()

3

## Agrupar datos 
df.groupby()
* Con este código podemos agrupar columnas e incluso otros dataframes y aplicarles alguna acción, como en este caso con los promedios, conteos por categoría.

Para el groupby, escribimos:
df.groupby("categoría")[["columnas que querémos"]]

In [19]:
#el primer () debe ser un dato categorico
df.groupby("col10")[["col1","col3","col4","col7","col8"]].mean()

             col1       col3      col4      col7      col8
col10
Alto   480.194412  51.141176  4.294118  0.489353  2.794118
Bajo   473.109722  46.633333  5.083333  0.500250  3.000000
Medio  472.979000  47.156667  4.766667  0.491600  2.900000

In [20]:
df.groupby(["col10"])[["col1","col3","col4","col7","col8"]].count()

       col1  col3  col4  col7  col8
col10
Alto     34    34    34    34    34
Bajo     36    36    36    36    36
Medio    30    30    30    30    30

## Crear y modificar columnas 
Para crear variables apartir de las existentes usamos:
df["nueva columna"] = las características que quieres que tenga. Por ejemplo:

In [21]:
df["col11"] = df["col1"]*10
df["col12"] = df["col3"] + df["col8"]

In [22]:
display(df)

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12
0,380.79,49,56.4,1,B,Sur,0.294,5,No,Alto,3807.9,61.4
1,951.21,56,13.0,9,A,Oeste,0.996,2,Sí,Medio,9512.1,15.0
2,734.67,49,57.2,2,C,Norte,0.697,5,Sí,Alto,7346.7,62.2
3,602.67,21,63.9,0,A,Norte,0.384,3,Sí,Alto,6026.7,66.9
4,164.46,47,37.4,7,D,Sur,0.737,3,Sí,Medio,1644.6,40.4
...,...,...,...,...,...,...,...,...,...,...,...,...
95,498.86,43,47.7,8,B,Sur,0.459,2,Sí,Bajo,4988.6,49.7
96,527.51,20,44.4,6,C,Este,0.842,2,Sí,Alto,5275.1,46.4
97,433.27,36,30.6,3,D,Norte,0.769,3,Sí,Bajo,4332.7,33.6
98,35.16,37,38.5,9,A,Norte,0.066,3,Sí,Bajo,351.6,41.5
99,116.81,49,56.3,4,B,Sur,0.046,5,Sí,Bajo,1168.1,61.3